[project]
name = "adlcv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "datasets==3.2.0",
    "diffusers>=0.37.0",
    "einops==0.8.1",
    "matplotlib>=3.10.8",
    "numpy==2.2.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "tensorboard>=2.20.0",
    "torch==2.6.0",
    "torchtext==0.6.0",
    "torchvision>=0.21.0",
    "tqdm==4.67.1",
    "transformers==4.48.3",
]
